version: "3.9"

services:
  federated_db:
    image: mysql:5.7
    container_name: alphamed-federated-database
    volumes:
      - db_data:/var/lib/mysql
      - database_init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: alpha&federated
      MYSQL_USER: federated
      MYSQL_PASSWORD: alpha&federated
      MYSQL_DATABASE: federated_db
      TZ: Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max_allowed_packet=200M']
  
  alphamed_minio:
    image: minio/minio
    container_name: alphamed-minio
    ports:
      - 9030:9000
      - 9040:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data

  playground-dataset:
    container_name: playground-dataset
    image: mirrors-sspedu.tencentcloudcr.com/alphamed-hub/playground-dataset:v2.3
    ports:
      - 9020:80
    environment:
      NODE_ENV: ${NODE_ENV}
      MINIO_HOSTNAME: ${MINIO_HOSTNAME}

  chain-connector:
    depends_on:
      - federated_db
    image: mirrors-sspedu.tencentcloudcr.com/alphamed-hub/chain-connector:v2.3
    container_name: alphamed-chain-connector
    ports:
      - "9070:9070"
    restart: always

  federated-service:
    depends_on:
      - federated_db
    container_name: alphamed-federated-service
    shm_size: 2gb    
    image: mirrors-sspedu.tencentcloudcr.com/alphamed-hub/federated-service:v2.3_cuda11
    ports:
      - "9080:9080"
      - "21010-21020:21010-21020"
    restart: always
    volumes:
      - runtime_data:/data/alphamed-federated
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]      

  playground-jupyter:
    depends_on:
      - federated-service
    container_name: alphamed-federated-playground-jupyter
    shm_size: 24gb
    hostname: playground-jupyter
    image: mirrors-sspedu.tencentcloudcr.com/alphamed-hub/playground-jupyter:v2.3_cuda11
    ports:
      - "9010:8000"
    restart: always
    volumes:
      - runtime_data:/data/alphamed-federated:ro
      - code_data:/app/db
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]      

volumes:
  db_data: {}
  runtime_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-runtime  
  code_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-code
  database_init:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-database/init
  minio_storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-storage      
