version: "3.9"

services:
  federated_db:
    image: mysql:5.7
    container_name: alphamed-federated-database
    volumes:
      - db_data:/var/lib/mysql
      - databse_init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: alpha&federated
      MYSQL_USER: federated
      MYSQL_PASSWORD: alpha&federated
      # MYSQL_DATABASE: federated_db
      TZ: Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max_allowed_packet=200M']

  alphamed_minio:
    image: minio/minio
    container_name: alphamed-minio
    ports:
      - 9030:9000
      - 9040:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data

  playground-dataset:
    container_name: playground-dataset
    build:
      context: git@github.com:ssplabs/nodejs-api-playground-node.git#dev
      dockerfile: Dockerfile
      network: host
    ports:
      - 9020:80
    environment:
      NODE_ENV: ${NODE_ENV}
      MINIO_HOSTNAME: ${MINIO_HOSTNAME}

  chain-connector:
    depends_on:
      - federated_db
    container_name: alphamed-chain-connector
    build:
      context: git@github.com:ssplabs/ssplabs-chain-connector.git#master
      dockerfile: Dockerfile
      network: host
    ports:
      - "9070:9070"
    restart: always

  playground-backend:
    depends_on:
      - federated_db
      - chain-connector
    container_name: alphamed-playground-backend
    build:
      context: git@github.com:ssplabs/playground-backend.git#develop
      dockerfile: Dockerfile
      network: host
    ports:
      - "9060:9060"
    restart: always

  federated-service:
    depends_on:
      - federated_db
      - chain-connector
    container_name: alphamed-federated-service
    build:
      context: git@github.com:ssplabs/federated-service.git#develop
      dockerfile: Dockerfile
      network: host
    environment:
      FED_ENV: "${FED_ENV}"
    ports:
      - "9080:9080"
      - "21010-21020:21010-21020"
    restart: always
    volumes:
      - runtime_data:/data/alphamed-federated

  playground-jupyter:
    depends_on:
      - playground-backend
    container_name: alphamed-federated-playground-jupyter

    hostname: playground-jupyter
    build:
      context: git@github.com:ssplabs/playground-jupyter.git#develop
      dockerfile: Dockerfile
      network: host
    ports:
      - "9010:8000"
    restart: always
    volumes:
      - runtime_data:/data/alphamed-federated:ro
      - code_data:/app/db

volumes:
  db_data: {}
  runtime_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-runtime
  code_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-code
  databse_init:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-database/init
  minio_storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/alphamed/alphamed-storage