local_chain: true
fed_node:
  org_id: "alphamed-ssplabs"
  org_name: "alphamedSSPLabs"
  node_name: "ssplabsCVMBJ001"
  node_host: 192.168.1.133
backend:
  host: 127.0.0.1
chain:
  chain_id: "alphamed_federated_network"
  org_id: "nst-state-lab-bupt"
  org_name: "nstStateLabBUPT"
  node_name: "buptCVM001"
  node_id: "QmfFQ1CDXU8kYGMSkqPGqMw7NfnjGsfr3jPU9GbSBY4P3J"
  user_name: "buptAdmin01"
  node_host: "172.27.0.5" # "127.0.0.1"
  node_rpc_port: 12301
  tls: true
  tls_host_name: "chainmaker.org"
  contract:
  - name: "fact"
    version: "2.0"
  - name: "task"
    version: "1.0"
  cert:
    org_ca: ../configs/cert/org.crt
    user_tls_cert: ../configs/cert/user.tls.crt
    user_tls_key: ../configs/cert/user.tls.key
    user_sign_cert: ../configs/cert/user.sign.crt
    user_sign_key: ../configs/cert/user.sign.key
